// <auto-generated />
using Application.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(ProgramAppDbContext))]
    [Migration("20240516134551_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Entities.Answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CandidateApplicationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomQuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateApplicationId");

                    b.HasIndex("CustomQuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Domain.Models.Entities.CandidateApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("CandidateApplications");
                });

            modelBuilder.Entity("Domain.Models.Entities.Choice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnswerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChoiceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("Domain.Models.Entities.CustomQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("MaxChoiceAllowed")
                        .HasColumnType("tinyint");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("CustomQuestions");
                });

            modelBuilder.Entity("Domain.Models.Entities.Program", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Domain.Models.Entities.Question", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Domain.Models.Entities.Answer", b =>
                {
                    b.HasOne("Domain.Models.Entities.CandidateApplication", "CandidateApplication")
                        .WithMany("Answers")
                        .HasForeignKey("CandidateApplicationId");

                    b.HasOne("Domain.Models.Entities.CustomQuestion", "CustomQuestion")
                        .WithMany()
                        .HasForeignKey("CustomQuestionId");

                    b.HasOne("Domain.Models.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateApplication");

                    b.Navigation("CustomQuestion");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Models.Entities.CandidateApplication", b =>
                {
                    b.HasOne("Domain.Models.Entities.Program", "Program")
                        .WithMany("CandidateApplications")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Models.Entities.Choice", b =>
                {
                    b.HasOne("Domain.Models.Entities.Answer", "Answer")
                        .WithMany("Choices")
                        .HasForeignKey("AnswerId");

                    b.HasOne("Domain.Models.Entities.CustomQuestion", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Answer");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Models.Entities.CustomQuestion", b =>
                {
                    b.HasOne("Domain.Models.Entities.Program", "Program")
                        .WithMany("CustomQuestions")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Models.Entities.Question", b =>
                {
                    b.HasOne("Domain.Models.Entities.Program", "Program")
                        .WithMany("Questions")
                        .HasForeignKey("ProgramId");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Domain.Models.Entities.Answer", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Domain.Models.Entities.CandidateApplication", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Domain.Models.Entities.CustomQuestion", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Domain.Models.Entities.Program", b =>
                {
                    b.Navigation("CandidateApplications");

                    b.Navigation("CustomQuestions");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
